Document: hpodder
Title: Debian hpodder Manual
Author: <insert document author here>
Abstract: This manual describes what hpodder is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/hpodder/hpodder.sgml.gz

Format: postscript
Files: /usr/share/doc/hpodder/hpodder.ps.gz

Format: text
Files: /usr/share/doc/hpodder/hpodder.text.gz

Format: HTML
Index: /usr/share/doc/hpodder/html/index.html
Files: /usr/share/doc/hpodder/html/*.html

  
